=== OGF-GLUE/JSON/schema/Glue2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Glue2.json",
  "description": "A GLUE 2 document",
  "type": "object",
  "properties": {
    "Entity": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Entity.json"}]
      }
    },
    "Location": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Location.json"}]
      }
    },
    "Contact": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Contact.json"}]
      }
    },
    "Domain": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Domain.json"}]
      }
    },
    "AdminDomain": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/AdminDomain.json"}]
      }
    },
    "UserDomain": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/UserDomain.json"}]
      }
    },
    "Service": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Service.json"}]
      }
    },
    "Endpoint": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Endpoint.json"}]
      }
    },
    "Share": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Share.json"}]
      }
    },
    "Manager": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Manager.json"}]
      }
    },
    "Resource": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Resource.json"}]
      }
    },
    "Activity": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Activity.json"}]
      }
    },
    "Policy": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Policy.json"}]
      }
    },
    "AccessPolicy": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/AccessPolicy.json"}]
      }
    },
    "MappingPolicy": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/MappingPolicy.json"}]
      }
    },
    "ComputingService": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ComputingService.json"}]
      }
    },
    "ComputingEndpoint": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ComputingEndpoint.json"}]
      }
    },
    "ComputingShare": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ComputingShare.json"}]
      }
    },
    "ComputingManager": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ComputingManager.json"}]
      }
    },
    "Benchmark": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/Benchmark.json"}]
      }
    },
    "ExecutionEnvironment": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ExecutionEnvironment.json"}]
      }
    },
    "ApplicationEnvironment": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ApplicationEnvironment.json"}]
      }
    },
    "ApplicationHandle": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ApplicationHandle.json"}]
      }
    },
    "ComputingActivity": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ComputingActivity.json"}]
      }
    },
    "ToStorageService": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ToStorageService.json"}]
      }
    },
    "StorageService": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageService.json"}]
      }
    },
    "StorageServiceCapacity": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageServiceCapacity.json"}]
      }
    },
    "StorageAccessProtocol": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageAccessProtocol.json"}]
      }
    },
    "StorageEndpoint": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageEndpoint.json"}]
      }
    },
    "StorageShare": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageShare.json"}]
      }
    },
    "StorageShareCapacity": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageShareCapacity.json"}]
      }
    },
    "StorageManager": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/StorageManager.json"}]
      }
    },
    "DataStore": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/DataStore.json"}]
      }
    },
    "ToComputingService": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [{"$ref": "http://schemas.ogf.org/glue/2013/05/spec_2.0/ToComputingService.json"}]
      }
    }
  }
}

=== OGF-GLUE/JSON/examples/compute_openstack.json
{
  "ComputingEndpoint": [
    {
      "Associations": {
        "ServiceID": "urn:glue2:ComputingService:openstack.alamo.futuregrid.org"
      }, 
      "Capability": [
        "executionmanagement.jobdescription", 
        "executionmanagement.jobexecution", 
        "executionmanagement.jobmanager"
      ], 
      "CreationTime": "2014-03-26T15:10:05Z", 
      "HealthState": "unknown", 
      "ID": "urn:glue2:ComputingEndpoint:openstack-ec2.openstack.alamo.futuregrid.org", 
      "ImplementationName": "OpenStack", 
      "ImplementationVersion": "2012.2", 
      "Implementor": "OpenStack", 
      "InterfaceName": "EC2", 
      "Name": "openstack-ec2", 
      "QualityLevel": "production", 
      "ServingState": "production", 
      "Technology": "REST", 
      "URL": "https://openstack.futuregrid.tacc.utexas.edu:8773/services/Cloud"
    }, 
    {
      "Associations": {
        "ServiceID": "urn:glue2:ComputingService:openstack.alamo.futuregrid.org"
      }, 
      "Capability": [
        "executionmanagement.jobdescription", 
        "executionmanagement.jobexecution", 
        "executionmanagement.jobmanager"
      ], 
      "CreationTime": "2014-03-26T15:10:05Z", 
      "HealthState": "unknown", 
      "ID": "urn:glue2:ComputingEndpoint:openstack-nova.openstack.alamo.futuregrid.org", 
      "ImplementationName": "OpenStack", 
      "ImplementationVersion": "2012.2", 
      "Implementor": "OpenStack", 
      "InterfaceName": "Nova", 
      "Name": "openstack-nova", 
      "QualityLevel": "production", 
      "ServingState": "production", 
      "Technology": "REST", 
      "URL": "https://openstack.alamo.futuregrid.org:$(compute_port)s/v1.1/$(tenant_id)s"
    }
  ], 
  "ComputingManager": [
    {
      "Associations": {
        "ServiceID": "urn:glue2:ComputingService:openstack.alamo.futuregrid.org"
      }, 
      "BulkSubmission": true, 
      "CreationTime": "2014-03-26T15:10:20Z", 
      "Homogeneous": true, 
      "ID": "urn:glue2:ComputingManager:openstack.alamo.futuregrid.org", 
      "Name": "OpenStack", 
      "ProductName": "OpenStack", 
      "Reservation": false, 
      "Resource": [
        "urn:glue2:ExecutionEnvironment:NodeType1.openstack.alamo.futuregrid.org"
      ], 
      "TotalLogicalCPUs": 120, 
      "TotalSlots": 120, 
      "Version": "2012.2"
    }
  ], 
  "ComputingService": [
    {
      "Associations": {
        "EndpointID": [
          "urn:glue2:ComputingEndpoint:openstack-ec2.openstack.alamo.futuregrid.org", 
          "urn:glue2:ComputingEndpoint:openstack-nova.openstack.alamo.futuregrid.org"
        ], 
        "LocationID": "urn:glue2:Location:TexasAdvancedComputingCenter", 
        "ManagerID": [
          "urn:glue2:ComputingManager:openstack.alamo.futuregrid.org"
        ]
      }, 
      "Capability": [
        "executionmanagement.jobexecution", 
        "executionmanagement.jobdescription", 
        "executionmanagement.jobmanager"
      ], 
      "CreationTime": "2014-03-26T15:10:20Z", 
      "ID": "urn:glue2:ComputingService:openstack.alamo.futuregrid.org", 
      "Name": "OpenStack", 
      "PreLRMSWaitingJobs": 0, 
      "QualityLevel": "production", 
      "RunningJobs": 22, 
      "StagingJobs": 0, 
      "SuspendedJobs": 0, 
      "TotalJobs": 22, 
      "Type": "org.openstack", 
      "WaitingJobs": 0
    }
  ], 
  "ExecutionEnvironment": [
    {
      "Associations": {
        "ManagerID": "urn:glue2:ComputingManager:openstack.alamo.futuregrid.org"
      }, 
      "ConnectivityIn": true,
      "ConnectivityOut": true,
      "CreationTime": "2014-03-26T15:10:05Z", 
      "Extension": {
        "DiskSize": 446
      }, 
      "ID": "urn:glue2:ExecutionEnvironment:NodeType1.openstack.alamo.futuregrid.org", 
      "LogicalCPUs": 8, 
      "MainMemorySize": 12005, 
      "Name": "NodeType1", 
      "OSFamily": "linux", 
      "OSName": "linux", 
      "OSVersion": "X.Y.Z", 
      "Platform": "x86_64", 
      "TotalInstances": 15, 
      "UnavailableInstances": 0, 
      "UsedInstances": 15
    }
  ], 
  "Location": [
    {
      "Country": "US", 
      "CreationTime": "2014-03-26T15:10:05Z", 
      "ID": "urn:glue2:Location:TexasAdvancedComputingCenter", 
      "Latitude": 30.390132, 
      "Longitude": -97.725309, 
      "Name": "Texas Advanced Computing Center", 
      "Place": "Austin", 
      "Validity": 86400
    }
  ]
}
